// Mocks generated by Mockito 5.4.0 from annotations
// in moviegoers/test/_utils/mock/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:moviegoers/src/core/init/network/network_exception.dart'
    as _i11;
import 'package:moviegoers/src/data/datasources/remote/movie/movie_remote_data_source.dart'
    as _i19;
import 'package:moviegoers/src/data/models/movie/movie/movie_model.dart'
    as _i20;
import 'package:moviegoers/src/data/models/movie/movie_credit/movie_credit_model.dart'
    as _i4;
import 'package:moviegoers/src/data/models/movie/movie_detail/movie_detail_model.dart'
    as _i3;
import 'package:moviegoers/src/data/models/movie/movie_external_id/movie_external_id_model.dart'
    as _i5;
import 'package:moviegoers/src/data/models/movie/movie_keywords/movie_keywords_model.dart'
    as _i8;
import 'package:moviegoers/src/data/models/movie/movie_provider/movie_provider_model.dart'
    as _i6;
import 'package:moviegoers/src/data/models/movie/movie_video/movie_video_model.dart'
    as _i7;
import 'package:moviegoers/src/domain/entities/movie/movie/movie.dart' as _i12;
import 'package:moviegoers/src/domain/entities/movie/movie_credit/movie_credit.dart'
    as _i14;
import 'package:moviegoers/src/domain/entities/movie/movie_detail/movie_detail.dart'
    as _i13;
import 'package:moviegoers/src/domain/entities/movie/movie_external_id/movie_external_id.dart'
    as _i15;
import 'package:moviegoers/src/domain/entities/movie/movie_keywords/movie_keywords.dart'
    as _i18;
import 'package:moviegoers/src/domain/entities/movie/movie_provider/movie_provider.dart'
    as _i17;
import 'package:moviegoers/src/domain/entities/movie/movie_video/movie_video.dart'
    as _i16;
import 'package:moviegoers/src/domain/repositories/movie_repository.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieDetailModel_1 extends _i1.SmartFake
    implements _i3.MovieDetailModel {
  _FakeMovieDetailModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieCreditModel_2 extends _i1.SmartFake
    implements _i4.MovieCreditModel {
  _FakeMovieCreditModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieExternalIdModel_3 extends _i1.SmartFake
    implements _i5.MovieExternalIdModel {
  _FakeMovieExternalIdModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieProviderModel_4 extends _i1.SmartFake
    implements _i6.MovieProviderModel {
  _FakeMovieProviderModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieVideoModel_5 extends _i1.SmartFake
    implements _i7.MovieVideoModel {
  _FakeMovieVideoModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieKeywordsModel_6 extends _i1.SmartFake
    implements _i8.MovieKeywordsModel {
  _FakeMovieKeywordsModel_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i9.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<
      _i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>> getPopularMovies(
          {required int? page}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
          {#page: page},
        ),
        returnValue: _i10.Future<
                _i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>.value(
            _FakeEither_0<_i11.NetworkExceptions, List<_i12.Movie>?>(
          this,
          Invocation.method(
            #getPopularMovies,
            [],
            {#page: page},
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>);
  @override
  _i10.Future<_i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>
      getNowPlayingMovies({required int? page}) => (super.noSuchMethod(
            Invocation.method(
              #getNowPlayingMovies,
              [],
              {#page: page},
            ),
            returnValue: _i10.Future<
                    _i2.Either<_i11.NetworkExceptions,
                        List<_i12.Movie>?>>.value(
                _FakeEither_0<_i11.NetworkExceptions, List<_i12.Movie>?>(
              this,
              Invocation.method(
                #getNowPlayingMovies,
                [],
                {#page: page},
              ),
            )),
          ) as _i10
              .Future<_i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>);
  @override
  _i10.Future<
      _i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>> getUpcomingMovies(
          {required int? page}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingMovies,
          [],
          {#page: page},
        ),
        returnValue: _i10.Future<
                _i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>.value(
            _FakeEither_0<_i11.NetworkExceptions, List<_i12.Movie>?>(
          this,
          Invocation.method(
            #getUpcomingMovies,
            [],
            {#page: page},
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>);
  @override
  _i10.Future<
      _i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>> getTopRatedMovies(
          {required int? page}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
          {#page: page},
        ),
        returnValue: _i10.Future<
                _i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>.value(
            _FakeEither_0<_i11.NetworkExceptions, List<_i12.Movie>?>(
          this,
          Invocation.method(
            #getTopRatedMovies,
            [],
            {#page: page},
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>);
  @override
  _i10.Future<_i2.Either<_i11.NetworkExceptions, _i13.MovieDetail>>
      getMovieDetails({required String? movieID}) => (super.noSuchMethod(
            Invocation.method(
              #getMovieDetails,
              [],
              {#movieID: movieID},
            ),
            returnValue: _i10.Future<
                    _i2.Either<_i11.NetworkExceptions, _i13.MovieDetail>>.value(
                _FakeEither_0<_i11.NetworkExceptions, _i13.MovieDetail>(
              this,
              Invocation.method(
                #getMovieDetails,
                [],
                {#movieID: movieID},
              ),
            )),
          ) as _i10
              .Future<_i2.Either<_i11.NetworkExceptions, _i13.MovieDetail>>);
  @override
  _i10.Future<_i2.Either<_i11.NetworkExceptions, _i14.MovieCredit>>
      getMovieCredits({required String? movieID}) => (super.noSuchMethod(
            Invocation.method(
              #getMovieCredits,
              [],
              {#movieID: movieID},
            ),
            returnValue: _i10.Future<
                    _i2.Either<_i11.NetworkExceptions, _i14.MovieCredit>>.value(
                _FakeEither_0<_i11.NetworkExceptions, _i14.MovieCredit>(
              this,
              Invocation.method(
                #getMovieCredits,
                [],
                {#movieID: movieID},
              ),
            )),
          ) as _i10
              .Future<_i2.Either<_i11.NetworkExceptions, _i14.MovieCredit>>);
  @override
  _i10.Future<_i2.Either<_i11.NetworkExceptions, _i15.MovieExternalId>>
      getMovieExternalIDs({required String? movieID}) => (super.noSuchMethod(
            Invocation.method(
              #getMovieExternalIDs,
              [],
              {#movieID: movieID},
            ),
            returnValue: _i10.Future<
                    _i2.Either<_i11.NetworkExceptions,
                        _i15.MovieExternalId>>.value(
                _FakeEither_0<_i11.NetworkExceptions, _i15.MovieExternalId>(
              this,
              Invocation.method(
                #getMovieExternalIDs,
                [],
                {#movieID: movieID},
              ),
            )),
          ) as _i10.Future<
              _i2.Either<_i11.NetworkExceptions, _i15.MovieExternalId>>);
  @override
  _i10.Future<_i2.Either<_i11.NetworkExceptions, _i16.MovieVideo>>
      getMovieVideos({required String? movieID}) => (super.noSuchMethod(
            Invocation.method(
              #getMovieVideos,
              [],
              {#movieID: movieID},
            ),
            returnValue: _i10.Future<
                    _i2.Either<_i11.NetworkExceptions, _i16.MovieVideo>>.value(
                _FakeEither_0<_i11.NetworkExceptions, _i16.MovieVideo>(
              this,
              Invocation.method(
                #getMovieVideos,
                [],
                {#movieID: movieID},
              ),
            )),
          ) as _i10
              .Future<_i2.Either<_i11.NetworkExceptions, _i16.MovieVideo>>);
  @override
  _i10.Future<_i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>
      getMovieRecommendations({
    required String? movieID,
    required int? page,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getMovieRecommendations,
              [],
              {
                #movieID: movieID,
                #page: page,
              },
            ),
            returnValue: _i10.Future<
                    _i2.Either<_i11.NetworkExceptions,
                        List<_i12.Movie>?>>.value(
                _FakeEither_0<_i11.NetworkExceptions, List<_i12.Movie>?>(
              this,
              Invocation.method(
                #getMovieRecommendations,
                [],
                {
                  #movieID: movieID,
                  #page: page,
                },
              ),
            )),
          ) as _i10
              .Future<_i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>);
  @override
  _i10.Future<
      _i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>> getMovieSimilars({
    required String? movieID,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieSimilars,
          [],
          {
            #movieID: movieID,
            #page: page,
          },
        ),
        returnValue: _i10.Future<
                _i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>.value(
            _FakeEither_0<_i11.NetworkExceptions, List<_i12.Movie>?>(
          this,
          Invocation.method(
            #getMovieSimilars,
            [],
            {
              #movieID: movieID,
              #page: page,
            },
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.NetworkExceptions, List<_i12.Movie>?>>);
  @override
  _i10.Future<
      _i2.Either<_i11.NetworkExceptions, _i17.MovieProvider>> getMovieProviders(
          {required String? movieID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieProviders,
          [],
          {#movieID: movieID},
        ),
        returnValue: _i10.Future<
                _i2.Either<_i11.NetworkExceptions, _i17.MovieProvider>>.value(
            _FakeEither_0<_i11.NetworkExceptions, _i17.MovieProvider>(
          this,
          Invocation.method(
            #getMovieProviders,
            [],
            {#movieID: movieID},
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.NetworkExceptions, _i17.MovieProvider>>);
  @override
  _i10.Future<
      _i2.Either<_i11.NetworkExceptions, _i18.MovieKeywords>> getMovieKeywords(
          {required String? movieID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieKeywords,
          [],
          {#movieID: movieID},
        ),
        returnValue: _i10.Future<
                _i2.Either<_i11.NetworkExceptions, _i18.MovieKeywords>>.value(
            _FakeEither_0<_i11.NetworkExceptions, _i18.MovieKeywords>(
          this,
          Invocation.method(
            #getMovieKeywords,
            [],
            {#movieID: movieID},
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.NetworkExceptions, _i18.MovieKeywords>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i19.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i20.MovieModel>?> getPopularMovies({required int? page}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
          {#page: page},
        ),
        returnValue: _i10.Future<List<_i20.MovieModel>?>.value(),
      ) as _i10.Future<List<_i20.MovieModel>?>);
  @override
  _i10.Future<List<_i20.MovieModel>?> getNowPlayingMovies(
          {required int? page}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingMovies,
          [],
          {#page: page},
        ),
        returnValue: _i10.Future<List<_i20.MovieModel>?>.value(),
      ) as _i10.Future<List<_i20.MovieModel>?>);
  @override
  _i10.Future<List<_i20.MovieModel>?> getUpcomingMovies({required int? page}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingMovies,
          [],
          {#page: page},
        ),
        returnValue: _i10.Future<List<_i20.MovieModel>?>.value(),
      ) as _i10.Future<List<_i20.MovieModel>?>);
  @override
  _i10.Future<List<_i20.MovieModel>?> getTopRatedMovies({required int? page}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
          {#page: page},
        ),
        returnValue: _i10.Future<List<_i20.MovieModel>?>.value(),
      ) as _i10.Future<List<_i20.MovieModel>?>);
  @override
  _i10.Future<_i3.MovieDetailModel> getMovieDetails(
          {required String? movieID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetails,
          [],
          {#movieID: movieID},
        ),
        returnValue:
            _i10.Future<_i3.MovieDetailModel>.value(_FakeMovieDetailModel_1(
          this,
          Invocation.method(
            #getMovieDetails,
            [],
            {#movieID: movieID},
          ),
        )),
      ) as _i10.Future<_i3.MovieDetailModel>);
  @override
  _i10.Future<_i4.MovieCreditModel> getMovieCredits(
          {required String? movieID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieCredits,
          [],
          {#movieID: movieID},
        ),
        returnValue:
            _i10.Future<_i4.MovieCreditModel>.value(_FakeMovieCreditModel_2(
          this,
          Invocation.method(
            #getMovieCredits,
            [],
            {#movieID: movieID},
          ),
        )),
      ) as _i10.Future<_i4.MovieCreditModel>);
  @override
  _i10.Future<_i5.MovieExternalIdModel> getMovieExternalIDs(
          {required String? movieID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieExternalIDs,
          [],
          {#movieID: movieID},
        ),
        returnValue: _i10.Future<_i5.MovieExternalIdModel>.value(
            _FakeMovieExternalIdModel_3(
          this,
          Invocation.method(
            #getMovieExternalIDs,
            [],
            {#movieID: movieID},
          ),
        )),
      ) as _i10.Future<_i5.MovieExternalIdModel>);
  @override
  _i10.Future<_i6.MovieProviderModel> getMovieProviders(
          {required String? movieID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieProviders,
          [],
          {#movieID: movieID},
        ),
        returnValue:
            _i10.Future<_i6.MovieProviderModel>.value(_FakeMovieProviderModel_4(
          this,
          Invocation.method(
            #getMovieProviders,
            [],
            {#movieID: movieID},
          ),
        )),
      ) as _i10.Future<_i6.MovieProviderModel>);
  @override
  _i10.Future<_i7.MovieVideoModel> getMovieVideos({required String? movieID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieVideos,
          [],
          {#movieID: movieID},
        ),
        returnValue:
            _i10.Future<_i7.MovieVideoModel>.value(_FakeMovieVideoModel_5(
          this,
          Invocation.method(
            #getMovieVideos,
            [],
            {#movieID: movieID},
          ),
        )),
      ) as _i10.Future<_i7.MovieVideoModel>);
  @override
  _i10.Future<List<_i20.MovieModel>?> getMovieRecommendations({
    required String? movieID,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieRecommendations,
          [],
          {
            #movieID: movieID,
            #page: page,
          },
        ),
        returnValue: _i10.Future<List<_i20.MovieModel>?>.value(),
      ) as _i10.Future<List<_i20.MovieModel>?>);
  @override
  _i10.Future<List<_i20.MovieModel>?> getMovieSimilars({
    required String? movieID,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieSimilars,
          [],
          {
            #movieID: movieID,
            #page: page,
          },
        ),
        returnValue: _i10.Future<List<_i20.MovieModel>?>.value(),
      ) as _i10.Future<List<_i20.MovieModel>?>);
  @override
  _i10.Future<_i8.MovieKeywordsModel> getMovieKeywords(
          {required String? movieID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieKeywords,
          [],
          {#movieID: movieID},
        ),
        returnValue:
            _i10.Future<_i8.MovieKeywordsModel>.value(_FakeMovieKeywordsModel_6(
          this,
          Invocation.method(
            #getMovieKeywords,
            [],
            {#movieID: movieID},
          ),
        )),
      ) as _i10.Future<_i8.MovieKeywordsModel>);
}
