include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "/test_local/**"
    - "**/*.g.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    - test
    
linter:
  rules:
    depend_on_referenced_packages: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    use_decorated_box: false
    type_annotate_public_apis: false