name: moviegoers
description: Moviegoers.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  auto_route: ^6.0.0+1
  auto_size_text: ^3.0.0
  connectivity_plus: ^3.0.3
  dartz: ^0.10.1
  dio: ^5.0.3
  dio_smart_retry: ^5.0.0
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flutter: 
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.4
  get_it: ^7.2.0
  json_serializable: ^6.6.1
  logging: ^1.1.1
  pretty_dio_logger: ^1.3.1
  rive: ^0.10.3
  url_launcher: ^6.1.10

dev_dependencies:
  auto_route_generator: ^6.0.0
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.5
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.4.2
  json_annotation: ^4.8.0 
  mockito: ^5.0.15
  mocktail: ^0.2.0
  very_good_analysis: ^4.0.0+1


flutter_gen:
  output: lib/src/config/gen/
  inputs:
    - assets/icons/

  colors:
      enabled: true
      outputs:
        class_name: MGColors
      inputs:
        - assets/colors/colors.xml


flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.development
    - languages/
    - assets/colors/
    - assets/icons/
    - assets/fonts/



  fonts:
    - family: Apercu
      fonts:
        - asset: assets/fonts/Apercu Pro Bold.otf
        - asset: assets/fonts/Apercu Pro Bold Italic.otf
          style: italic
        
        - asset: assets/fonts/Apercu Pro Regular.otf
        - asset: assets/fonts/Apercu Pro Italic.otf
          style: italic

        - asset: assets/fonts/Apercu Pro Light.otf
        - asset: assets/fonts/Apercu Pro Light Italic.otf
          style: italic

        - asset: assets/fonts/Apercu Pro Medium.otf
        - asset: assets/fonts/Apercu Pro Medium Italic.otf
          style: italic

        - asset: assets/fonts/Apercu Pro Mono.otf



